[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "PORT"
  VITE_API_BASE_URL = "https://eklavya-website.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
